#!/bin/bash

# Set default value for overwrite_disabled
overwrite_disabled=false

# Function to display usage message
usage() {
    echo "Usage: $0 [-d] [-h] [-g]"
    echo "-d: Disable overwrite functionality entirely"
    echo "-h: Display this help message"
    echo "-g: Generate symlinks for all installed flatpaks at once"
}

# Set paths for Flatpak exports and shortname bin
flatpak_bin_exports="$HOME/.local/share/flatpak/exports/bin"
shortname_bin_path="$HOME/.local/bin"

# Function to log info messages with a timestamp
log_info() {
    local message="$1"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[INFO] $timestamp - $message"
}

# Function to log error messages with a timestamp
log_error() {
    RED='\033[0;31m'
    NC='\033[0m'
    local message="$1"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "${RED}[ERROR] $timestamp - $message${NC}"
}

# Function to process a single modified Flatpak app
process_modified_flatpak() {
    local app_path="$1"
    local short_path="$2"
    local flatpak_name="$3"

    # Check if the symlink already exists
    if [[ -f "$short_path" ]]; then
        if $overwrite_disabled; then
            log_info "$flatpak_name installed, overwrite functionality is disabled. Skipping symlink creation"
        else
            log_info "$flatpak_name installed, overwriting existing file: $short_path"
            ln -sf "$app_path" "$short_path"
        fi
    else
        log_info "$flatpak_name installed, Symlinking $app_path to $short_path"
        ln -s "$app_path" "$short_path"
    fi
}

# Function to handle symlink creation and deletion
handle_symlink() {
    local event="$1"
    local flatpak_name="$2"
    local app_path="$3"

    if [ "$event" = "MOVED_TO" ]; then
        short_name=$(flatpak info $flatpak_name -m 2>/dev/null | grep command= | awk -F '=' '{print $2}' )

        # Check if short_name is empty or contains unexpected characters
        if [[ -z "$short_name" ]]; then
            log_error "Unable to extract a valid short_name for $flatpak_name. Skipping symlink creation"
        else
            short_path="$shortname_bin_path/$short_name"
            process_modified_flatpak "$app_path" "$short_path" "$flatpak_name"
        fi
    else
        log_info "App $flatpak_name uninstalled: Removing broken symlinks in $shortname_bin_path"
        find $shortname_bin_path -xtype l -delete
    fi
}

inotify_wait_forever() {
    # Monitor the directory for updates using inotifywait
    inotifywait -q -m -e MOVED_TO -e delete $flatpak_bin_exports |
    while read path event flatpak_name; do
        flatpak_app_path=$path$flatpak_name
        handle_symlink "$event" "$flatpak_name" "$flatpak_app_path"
    done
}

generate_all() {
    flatpaks=( $(ls "$flatpak_bin_exports") )
    [ -z "$flatpaks" ] && log_info "No installed flatpaks found" && exit 0

    echo "Found installed flatpaks:"
    for app in ${flatpaks[@]}; do echo " > $app"; done
    read -p "Do you want me to create symlinks for these flatpaks? [Y]" -n 1 -r
    echo    # (optional) move to a new line
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        for app in ${flatpaks[@]}; do 
            handle_symlink "MOVED_TO" "$app" "$flatpak_bin_exports/$app"
        done
    fi
}

# Parse command-line options
while getopts 'dhg' opt; do
    case "$opt" in
        d) overwrite_disabled=true ;;
        h) usage; exit 0 ;;
        g) generate_all; exit $? ;;
        *) usage; exit 1 ;;
    esac
done

# Shift positional parameters
shift $((OPTIND-1))

inotify_wait_forever